[package]
name = "ember-chess"
version = "1.3.1"
license = "MIT"
edition = "2021"
default-run = "ember"

[[bin]]
name = "ember"
path = "src/main.rs"

[lib]
name = "ember_chess"
path = "src/lib.rs"
 
[dependencies]
rand = { version = "0.8", features = ["small_rng"] }
pyrrhic-rs = { git = "https://github.com/starius/pyrrhic-rs", rev = "61bb83b7c46de492198b1565f45129e48f240c48" }

[dev-dependencies]
cozy-chess = "0.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(all(target_arch = "x86_64", any(target_os = "linux", target_os = "windows")))'.dependencies]
mimalloc = { version = "0.1.52", optional = true }

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_System_Threading"] }

[features]
default = ["mimalloc"]
decision-trace = []
mimalloc = ["dep:mimalloc"]
search-debug = []
search-perf = []
 
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
