"""Serialize independently verified lost-advantage candidates as TSV fixtures."""

import os
import tempfile
from pathlib import Path


STARTPOS_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
FIXTURE_HEADER = (
    "id\tdepth\tfen_before_blunder\tsetup_move\texpected_move"
    "\tthemes\trating\tpopularity\tplays"
)


def fixture_comment(case) -> str:
    best = case.stockfish_best_move or "unknown"
    loss = "unknown" if case.eval_loss_cp is None else str(case.eval_loss_cp)
    before = "unknown" if case.bad_score_cp_before is None else str(case.bad_score_cp_before)
    after = "unknown" if case.bad_score_cp_after is None else str(case.bad_score_cp_after)
    return (
        f"# Advantage-preservation hunt {case.case_id}. Source PGN: {case.source_pgn}; "
        f"replay PGN: {case.replay_pgn}. Ember was given a "
        f"{case.anchor_advantage_cp} cp Stockfish-confirmed advantage after original "
        f"ply {case.anchor_ply} ({case.anchor_move}), then lost advantage "
        f"bucket={case.bucket} at replay ply {case.bad_ply}: played {case.bad_move}, "
        f"Stockfish preferred {best}, eval before/after={before}/{after}, labeled "
        f"loss={loss} cp."
    )


def fixture_row(case) -> str:
    setup = " ".join(case.history_before_bad) if case.history_before_bad else "-"
    themes = f"advantagePreservation,stockfishHunt,{case.bucket}"
    return "\t".join(
        [
            case.case_id,
            str(case.bad_depth),
            STARTPOS_FEN,
            setup,
            "!" + case.bad_move,
            themes,
            "0",
            "0",
            "0",
        ]
    )


def validate_fixture_case(case) -> None:
    if case.stockfish_best_move is None:
        raise ValueError(f"{case.case_id}: missing Stockfish best move")
    if case.stockfish_best_move == case.bad_move:
        raise ValueError(
            f"{case.case_id}: played move matches the Stockfish best move"
        )
    if case.eval_loss_cp is None or case.eval_loss_cp <= 0:
        raise ValueError(
            f"{case.case_id}: expected positive evaluation-loss evidence"
        )


def write_fixture(path: Path, cases: list) -> None:
    for case in cases:
        validate_fixture_case(case)
    lines = [
        "# Advantage-preservation cases generated by tools/hunt_lost_advantage.py.",
        "# Rows stay disabled until the responsible bucket is understood and fixed.",
        FIXTURE_HEADER,
    ]
    for case in cases:
        lines.extend(
            [
                "",
                fixture_comment(case),
                "# DISABLED: collected for bucket triage; not fixed yet.",
                "# " + fixture_row(case),
            ]
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}.",
        suffix=".tmp",
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write("\n".join(lines) + "\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise
